---
- name: Configure interfaces
  hosts: "{{ hostlist | default('all') }}"
  gather_facts: no

  tasks:
    - name: Collect default set of facts
      junipernetworks.junos.junos_facts:
        config_format: json
        gather_subset: config
      register: facts_output

    - name: Print message
      debug:
        msg: "Configuring {{ item.name }} with IPv4 address {{ item.ipv4[0].address }}"
      with_items: "{{ srx_interfaces }}"

    - name: Ensure interface is configured
      junipernetworks.junos.junos_l3_interfaces:
        config: "{{ srx_interfaces }}"
        state: replaced
