---
- name: Create rescue configuration
  hosts: "{{ hostlist | default('all') }}"
  gather_facts: no

  tasks:
    - name: Collect default set of facts
      junipernetworks.junos.junos_facts:
        config_format: json
        gather_subset: config
      register: facts_output

    - name: Print message
      debug:
        msg: "Creating rescue configuration for {{ inventory_hostname }}"

#    - name: configurable backup path
#      junipernetworks.junos.junos_config:
#        backup: true
#        backup_options:
#          dir_path: /tmp/
#          filename: "{{ inventory_hostname }}.txt"
